name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      # Step 1: checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4
      
      # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build the Docker image
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    # Step 4: Tag the image with a unique tag (e.g., commit SHA or branch name)
    - name: Tag the Docker Image
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker tag my-image-name:latest my-dockerhub-username/my-image-name:${COMMIT_SHA}
        docker tag my-image-name:latest my-dockerhub-username/my-image-name:latest

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker Image
      run: |
        docker push my-dockerhub-username/my-image-name:${COMMIT_SHA}
        docker push my-dockerhub-username/my-image-name:latest